"""Unit conversions: convert_DO, convert_val, convert_MR, convert_rate.

Ported from respR 2.3.4 (GPL-3). Arithmetic mirrors the R source exactly so
results agree numerically with respR (validated in tests against reference
outputs generated by R).
"""
from __future__ import annotations

import re
import warnings
from dataclasses import dataclass, field

import numpy as np

from . import _marelac as ml
from ._units import (adjust_scale, adjust_scale_area, split_unit_string,
                     stp_check, stp_val, unit_type, unit_type_o1,
                     units_clean, units_val)


def _asnum(x):
    return np.asarray(x, dtype=float)


# ---------------------------------------------------------------------------
# convert_DO
# ---------------------------------------------------------------------------
def convert_DO(x, from_=None, to=None, S=None, t=None, P=None, simplify=True):
    """Convert dissolved oxygen concentrations between units.

    Parameters
    ----------
    x : array-like
        Oxygen concentration values.
    from_, to : str
        Oxygen units, e.g. 'mg/L', 'umol/L', '%Air', 'kPa'. See unit_args().
    S, t, P : float, optional
        Salinity (psu), temperature (degC), atmospheric pressure (bar).
        Required only for units that depend on physical conditions
        (e.g. %Air, mg/kg, kPa).
    simplify : bool
        If True (default) return just the converted values; if False return
        the full result object.

    Returns
    -------
    Converted values (or a ConvertDO result object if simplify=False).
    """
    z = _asnum(x)
    fru = units_val(from_, "o2", msg="convert_DO")
    tou = units_val(to, "o2", msg="convert_DO")
    P = stp_val(fru, "oxy", S, t, P, P_chk=False, msg="convert_DO")
    P = stp_val(tou, "oxy", S, t, P, P_chk=True, msg="convert_DO")

    if S is not None and np.ndim(S) > 0 and np.size(S) != 1 and np.size(S) != np.size(z):
        raise ValueError("convert_DO: The 'S' input must be a single value or the same length as the rates to be converted.")
    if t is not None and np.ndim(t) > 0 and np.size(t) != 1 and np.size(t) != np.size(z):
        raise ValueError("convert_DO: The 't' input must be a single value or the same length as the rates to be converted.")
    if P is not None and np.ndim(P) > 0 and np.size(P) != 1 and np.size(P) != np.size(z):
        raise ValueError("convert_DO: The 'P' input must be a single value or the same length as the rates to be converted.")

    StPreq = stp_check(fru, "oxy") or stp_check(tou, "oxy")
    if StPreq:
        omVl = np.asarray(ml.molvol(t=t, P=P, species="O2"), dtype=float)
        oGas = np.asarray(ml.gas_satconc(S=S, t=t, P=P, species="O2"), dtype=float)
        swDn = np.asarray(ml.sw_dens(S=S, t=t, P=P), dtype=float)
        vpor = np.asarray(ml.vapor(S=S, t=t), dtype=float)
    omWt = ml.molweight("O2")
    oAtm = ml.ATM_COMP["O2"]

    # ---- input unit -> mg/L ----
    if fru == "mg/L.o2":
        c = z
    elif fru == "ug/L.o2":
        c = z / 1000
    elif fru == "mol/L.o2":
        c = z * omWt * 1000
    elif fru == "mmol/L.o2":
        c = z * omWt
    elif fru == "umol/L.o2":
        c = z * omWt / 1000
    elif fru == "nmol/L.o2":
        c = z * omWt / 1e6
    elif fru == "pmol/L.o2":
        c = z * omWt / 1e9
    elif fru == "mL/L.o2":
        c = z * omWt / omVl
    elif fru == "uL/L.o2":
        c = z * omWt / omVl / 1000
    elif fru == "cm3/L.o2":
        c = z * omWt / omVl
    elif fru == "mm3/L.o2":
        c = z * omWt / omVl / 1000
    elif fru == "mg/kg.o2":
        c = z * swDn / 1000
    elif fru == "ug/kg.o2":
        c = z * swDn / 1e6
    elif fru == "mol/kg.o2":
        c = z * swDn * omWt
    elif fru == "mmol/kg.o2":
        c = z * swDn * omWt / 1000
    elif fru == "umol/kg.o2":
        c = z * swDn * omWt / 1e6
    elif fru == "nmol/kg.o2":
        c = z * swDn * omWt / 1e9
    elif fru == "pmol/kg.o2":
        c = z * swDn * omWt / 1e12
    elif fru == "%Air.o2":
        c = z * oGas * omWt / 1000 / 100
    elif fru == "%Oxy.o2":
        c = z * oGas * omWt / oAtm / 1000 / 100
    elif fru == "mL/kg.o2":
        c = z * omWt / omVl * swDn / 1000
    elif fru == "uL/kg.o2":
        c = z * omWt / omVl * swDn / 1e6
    elif fru == "cm3/kg.o2":
        c = z * omWt / omVl * swDn / 1000
    elif fru == "mm3/kg.o2":
        c = z * omWt / omVl * swDn / 1e6
    elif fru == "Torr.o2p":
        c = z / (P - vpor) / oAtm * oGas * omWt / 1000 / 760.00006600500001
    elif fru == "hPa.o2p":
        c = z / (P - vpor) / oAtm * oGas * omWt / 1000 / 1013.235
    elif fru == "kPa.o2p":
        c = z / (P - vpor) / oAtm * oGas * omWt / 1000 / 101.3235
    elif fru == "mmHg.o2p":
        c = z / (P - vpor) / oAtm * oGas * omWt / 1000 / 759.99995199600005
    elif fru == "inHg.o2p":
        c = z / (P - vpor) / oAtm * oGas * omWt / 1000 / 29.9212583001
    else:
        raise ValueError(f"convert_DO: unit '{from_}' not handled.")

    # ---- mg/L -> output unit ----
    if tou == "mg/L.o2":
        out = c
    elif tou == "ug/L.o2":
        out = c * 1000
    elif tou == "mol/L.o2":
        out = c / omWt / 1000
    elif tou == "mmol/L.o2":
        out = c / omWt
    elif tou == "umol/L.o2":
        out = c / omWt * 1000
    elif tou == "nmol/L.o2":
        out = c / omWt * 1e6
    elif tou == "pmol/L.o2":
        out = c / omWt * 1e9
    elif tou == "mL/L.o2":
        out = c / omWt * omVl
    elif tou == "uL/L.o2":
        out = c / omWt * omVl * 1000
    elif tou == "cm3/L.o2":
        out = c / omWt * omVl
    elif tou == "mm3/L.o2":
        out = c / omWt * omVl * 1000
    elif tou == "mg/kg.o2":
        out = c / swDn * 1000
    elif tou == "ug/kg.o2":
        out = c / swDn * 1e6
    elif tou == "mol/kg.o2":
        out = c / omWt / swDn
    elif tou == "mmol/kg.o2":
        out = c / omWt / swDn * 1000
    elif tou == "umol/kg.o2":
        out = c / omWt / swDn * 1e6
    elif tou == "nmol/kg.o2":
        out = c / omWt / swDn * 1e9
    elif tou == "pmol/kg.o2":
        out = c / omWt / swDn * 1e12
    elif tou == "%Air.o2":
        out = c / omWt / oGas * 1000 * 100
    elif tou == "%Oxy.o2":
        out = c / omWt / oGas * oAtm * 1000 * 100
    elif tou == "mL/kg.o2":
        out = c / swDn * omVl / omWt * 1000
    elif tou == "uL/kg.o2":
        out = c / swDn * omVl / omWt * 1e6
    elif tou == "cm3/kg.o2":
        out = c / swDn * omVl / omWt * 1000
    elif tou == "mm3/kg.o2":
        out = c / swDn * omVl / omWt * 1e6
    elif tou == "Torr.o2p":
        out = c / omWt / oGas * oAtm * (P - vpor) * 1000 * 760.00006600500001
    elif tou == "hPa.o2p":
        out = c / omWt / oGas * oAtm * (P - vpor) * 1000 * 1013.253
    elif tou == "kPa.o2p":
        out = c / omWt / oGas * oAtm * (P - vpor) * 1000 * 101.3253
    elif tou == "mmHg.o2p":
        out = c / omWt / oGas * oAtm * (P - vpor) * 1000 * 759.99995199600005
    elif tou == "inHg.o2p":
        out = c / omWt / oGas * oAtm * (P - vpor) * 1000 * 29.9212583001
    else:
        raise ValueError(f"convert_DO: unit '{to}' not handled.")

    fru_clean = units_clean(fru, "o2")
    tou_clean = units_clean(tou, "o2")
    if simplify:
        return out
    return ConvertDO(call=None, input=z, output=out, input_unit=fru_clean,
                     output_unit=tou_clean)


@dataclass
class ConvertDO:
    call: object
    input: np.ndarray
    output: np.ndarray
    input_unit: str
    output_unit: str


# ---------------------------------------------------------------------------
# convert_val
# ---------------------------------------------------------------------------
_PRESSURE_UNITS = ["kPa.p", "hPa.p", "Pa.p", "uBar.p", "mBar.p", "Bar.p", "atm.p", "Torr.p"]
_PRESSURE_MULT = [100.0, 1000.0, 100000.0, 1000000.0, 1000.0, 1.0, 0.98692, 750.06]


def convert_val(x, from_=None, to=None):
    """Convert values between simple units: volume, temperature, mass,
    area, or pressure. Mirrors respR::convert_val."""
    x = _asnum(x)
    if from_ is None:
        raise ValueError("convert_val: 'from' is required")
    fr_unit = unit_type(from_, msg="convert_val")
    if fr_unit not in ("vol", "temperature", "mass", "area", "pressure"):
        raise ValueError("convert_val: 'from' unit is not one of the accepted unit types.")
    if to is None:
        to = {"vol": "L", "temperature": "C", "mass": "kg", "area": "m2", "pressure": "bar"}[fr_unit]
    to_unit = unit_type(to, msg="convert_val")
    if to_unit not in ("vol", "temperature", "mass", "area", "pressure"):
        raise ValueError("convert_val: 'to' unit is not one of the accepted unit types.")
    if fr_unit != to_unit:
        raise ValueError("convert_val: 'from' and 'to' appear to be different unit types.")

    unit_fr = units_val(from_, fr_unit)
    unit_to = units_val(to, to_unit)

    if to_unit in ("vol", "mass"):
        out = adjust_scale(x, unit_fr, unit_to)
    elif to_unit == "area":
        out = adjust_scale_area(x, unit_fr, unit_to)
    elif to_unit == "pressure":
        mult_fr = _PRESSURE_MULT[_PRESSURE_UNITS.index(unit_fr)]
        mult_to = _PRESSURE_MULT[_PRESSURE_UNITS.index(unit_to)]
        out = x * (mult_to / mult_fr)
    else:  # temperature
        if unit_fr == "C.temp":
            if unit_to == "K.temp":
                out = x + 273.15
            elif unit_to == "F.temp":
                out = x * 9 / 5 + 32
            else:
                out = x
        elif unit_fr == "K.temp":
            if unit_to == "C.temp":
                out = x - 273.15
            elif unit_to == "F.temp":
                out = x * 9 / 5 - 459.67
            else:
                out = x
        else:  # F.temp
            if unit_to == "C.temp":
                out = (x - 32) * 5 / 9
            elif unit_to == "K.temp":
                out = (x + 459.67) * 5 / 9
            else:
                out = x
    return out


# ---------------------------------------------------------------------------
# convert_rate
# ---------------------------------------------------------------------------
@dataclass
class ConvertRate:
    """Result of convert_rate(). Mirrors the respR 'convert_rate' object."""
    call: object = None
    inputs: dict = field(default_factory=dict)
    dataframe: object = None
    summary: dict = field(default_factory=dict)
    rate_input: np.ndarray = None
    output_unit: str = None
    rate_output: np.ndarray = None

    def __repr__(self):
        return (f"<resprpy.ConvertRate n={np.size(self.rate_output)} "
                f"output.unit={self.output_unit!r}>")


def _rate_object_parts(x):
    """Extract (rate, summary) from a calc_rate/auto_rate/adjust_rate-like
    object (dataclass or dict), or (x, None) for plain numeric input."""
    if hasattr(x, "rate") and hasattr(x, "summary"):
        return x.rate, x.summary
    if isinstance(x, dict) and "rate" in x and "summary" in x:
        return x["rate"], x["summary"]
    return None, None


def convert_rate(x, oxy_unit=None, time_unit=None, output_unit=None,
                 volume=None, mass=None, area=None, S=None, t=None, P=None,
                 plot=False, **kwargs):
    """Convert metabolic (oxygen uptake) rates between units.

    respR equivalent: convert_rate(x, oxy.unit=..., time.unit=...,
    output.unit=..., volume=..., mass=..., area=..., S=..., t=..., P=...).

    Parameters
    ----------
    x : array-like or calc_rate/auto_rate/adjust_rate result
        The rate(s) in the original units (oxygen per time).
    oxy_unit : str
        Oxygen concentration unit of the original data, e.g. 'mg/L'.
    time_unit : str
        Time unit of the original data, e.g. 'sec', 'min', 'hour'.
    output_unit : str
        Desired rate unit, e.g. 'mg/h', 'umol/min/g', 'mL/h/kg'.
    volume : float
        Chamber volume (L). Required.
    mass, area : float, optional
        Organism mass (kg) or surface area (m2) for specific rates.
    S, t, P : float, optional
        Salinity, temperature, pressure (bar) if the units require them.
    """
    if oxy_unit is None or isinstance(oxy_unit, (int, float)):
        raise ValueError("convert_rate: The 'oxy.unit' of the original data is required.")
    if time_unit is None or isinstance(time_unit, (int, float)):
        raise ValueError("convert_rate: The 'time.unit' of the original data is required.")
    if output_unit is None and mass is None and area is None:
        warnings.warn("convert_rate: The 'output.unit' is not provided. Applying default: 'mg/h'")
        output_unit = "mg/h"
    if output_unit is None and mass is not None and area is None:
        warnings.warn("convert_rate: The 'output.unit' is not provided. Applying default: 'mg/h/kg'")
        output_unit = "mg/h/kg"
    if output_unit is None and mass is None and area is not None:
        warnings.warn("convert_rate: The 'output.unit' is not provided. Applying default: 'mg/h/m2'")
        output_unit = "mg/h/m2"
    if volume is None or not isinstance(volume, (int, float, np.number)):
        raise ValueError("convert_rate: The 'volume' input is required.")
    if mass is not None and area is not None:
        raise ValueError("convert_rate: Cannot have inputs for both 'mass' and 'area'.")

    rate_obj, summ_in = _rate_object_parts(x)
    if rate_obj is None:
        rate = _asnum(x)
        n = np.size(rate)
        summary = {"rank": np.arange(1, n + 1), "rate": np.asarray(rate).ravel()}
    else:
        rate = _asnum(rate_obj)
        summary = dict(summ_in)

    oxy = units_val(oxy_unit, "o2")
    time = units_val(time_unit, "time")
    ou = split_unit_string(output_unit)
    is_spec = len(ou) == 3
    if is_spec:
        if mass is not None and area is None:
            is_mass_spec, is_area_spec = True, False
        elif area is not None and mass is None:
            is_mass_spec, is_area_spec = False, True
        else:
            raise ValueError("convert_rate: 'output.unit' requires a value for 'mass' or 'area'")
    else:
        is_mass_spec = is_area_spec = False

    A = units_val(ou[0], "o1")
    B = units_val(ou[1], "time")
    if is_spec:
        C = units_val(ou[2], "mass" if is_mass_spec else "area")
    if not is_mass_spec and isinstance(mass, (int, float, np.number)):
        raise ValueError("convert_rate: A 'mass' has been entered, but a mass-specific unit has not been specified in 'output.unit'.")
    if not is_area_spec and isinstance(area, (int, float, np.number)):
        raise ValueError("convert_rate: An 'area' has been entered, but an area-specific unit has not been specified in 'output.unit'.")

    oxy_clean = units_clean(oxy, "o2")
    time_clean = units_clean(time, "time")
    out_clean = [re.sub(r"\..*", "", u) for u in (A, B)]
    if is_spec:
        out_clean.append(re.sub(r"\..*", "", C))
    out_clean[0] = out_clean[0] + "O2"
    output_clean = "/".join(out_clean)

    P = stp_val(oxy_clean, "oxy", S, t, P, P_chk=False, msg="convert_rate")
    P = stp_val(output_clean, "mr", S, t, P, P_chk=True, msg="convert_rate")
    for name, v in (("S", S), ("t", t), ("P", P)):
        if v is not None and np.ndim(v) > 0 and np.size(v) != 1:
            raise ValueError(f"convert_rate: The '{name}' input should be a single value. "
                             "Rates determined in different physical conditions should be analysed and converted separately.")

    # oxygen amount: convert rate to the concentration unit matching A
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        if A in ("pmol.o2", "nmol.o2", "umol.o2", "mmol.o2", "mol.o2"):
            RO2 = convert_DO(rate, oxy, "mmol/L", S, t, P)
            RO2 = adjust_scale(RO2, "mmol.o2", A)
        elif A in ("mg.o2", "ug.o2"):
            RO2 = convert_DO(rate, oxy, "mg/L", S, t, P)
            RO2 = adjust_scale(RO2, "mg.o2", A)
        elif A in ("mL.o2", "uL.o2"):
            RO2 = convert_DO(rate, oxy, "mL/L", S, t, P)
            RO2 = adjust_scale(RO2, "mL.o2", A)
        elif A == "cm3.o2":
            RO2 = convert_DO(rate, oxy, "cm3/L", S, t, P)
        elif A == "mm3.o2":
            RO2 = convert_DO(rate, oxy, "cm3/L", S, t, P) * 1000
        else:
            raise ValueError(f"convert_rate: output oxygen unit '{ou[0]}' not handled.")

    RO2 = adjust_scale(RO2, time, B)
    VO2 = RO2 * volume
    if is_mass_spec:
        multm = adjust_scale(mass, "kg.mass", C)
        VO2_mass_spec = VO2 / multm
    if is_area_spec:
        multm = adjust_scale_area(area, "m2.area", C)
        VO2_area_spec = VO2 / multm

    n = np.size(rate)
    if is_mass_spec:
        rate_output = np.broadcast_to(VO2_mass_spec, (n,))
        extra = {"rate.abs": np.broadcast_to(VO2, (n,)),
                 "rate.m.spec": np.broadcast_to(VO2_mass_spec, (n,)),
                 "rate.a.spec": np.full(n, np.nan)}
    elif is_area_spec:
        rate_output = np.broadcast_to(VO2_area_spec, (n,))
        extra = {"rate.abs": np.broadcast_to(VO2, (n,)),
                 "rate.m.spec": np.full(n, np.nan),
                 "rate.a.spec": np.broadcast_to(VO2_area_spec, (n,))}
    else:
        rate_output = np.broadcast_to(VO2, (n,))
        extra = {"rate.abs": np.broadcast_to(VO2, (n,)),
                 "rate.m.spec": np.full(n, np.nan),
                 "rate.a.spec": np.full(n, np.nan)}

    summary.update({
        "rate.input": np.broadcast_to(rate, (n,)),
        "oxy.unit": np.array([oxy_clean] * n),
        "time.unit": np.array([time_clean] * n),
        "volume": np.full(n, volume),
        "mass": np.full(n, np.nan if mass is None else mass),
        "area": np.full(n, np.nan if area is None else area),
        "S": np.full(n, np.nan if S is None else S),
        "t": np.full(n, np.nan if t is None else t),
        "P": np.full(n, np.nan if P is None else P),
        "output.unit": np.array([output_clean] * n),
        "rate.output": rate_output,
        **extra,
    })

    inputs = dict(x=x, oxy_unit=oxy_clean, time_unit=time_clean, output_unit=output_clean,
                  volume=volume, mass=mass, area=area, S=S, t=t, P=P)
    # R: keep the input dataframe for object inputs (calc_rate/auto_rate/
    # adjust_rate...); numeric input -> NULL
    df_in = getattr(x, "dataframe", None)
    return ConvertRate(call=None, inputs=inputs, dataframe=df_in,
                       summary=summary,
                       rate_input=np.broadcast_to(rate, (n,)),
                       output_unit=output_clean, rate_output=rate_output)


# ---------------------------------------------------------------------------
# convert_MR
# ---------------------------------------------------------------------------
def convert_MR(x, from_=None, to=None, S=None, t=None, P=None, quiet=False):
    """Convert metabolic rates between rate-unit strings, e.g.
    convert_MR(0.001, from_='mg/sec', to='umol/min/g', S=35, t=20).

    Mirrors respR::convert_MR. Accepts plain rates or a convert_rate result
    (then 'from' is extracted automatically)."""
    obj = hasattr(x, "rate_output") and hasattr(x, "summary")
    if obj:
        rate = np.asarray(x.rate_output, dtype=float)
        S = x.inputs.get("S") if S is None else S
        t = x.inputs.get("t") if t is None else t
        P = x.inputs.get("P") if P is None else P
        from_ = x.output_unit
    else:
        rate = _asnum(x)
    if to is None:
        raise ValueError("convert_MR: Please specify a 'to' unit.")
    if from_ is None:
        raise ValueError("convert_MR: Please specify a 'from' unit.")

    P = stp_val(from_, "mr", S, t, P, P_chk=False, msg="convert_MR")
    P = stp_val(to, "mr", S, t, P, P_chk=True, msg="convert_MR")
    for name, v in (("S", S), ("t", t), ("P", P)):
        if v is not None and np.ndim(v) > 0 and np.size(v) != 1:
            raise ValueError(
                f"convert_MR: The '{name}' input should be a single value. "
                "Rates determined in different physical conditions should be analysed and converted separately.")

    from_sep = split_unit_string(from_)
    to_sep = split_unit_string(to)
    if len(from_sep) != len(to_sep):
        raise ValueError(
            "convert_MR: Parsing of 'from' and/or 'to' units has failed. Check unit_args() for accepted units "
            "and formatting. They should *both* be absolute, mass-specific, or area-specific rates and use "
            "same general formatting.")

    from_types = [unit_type_o1(from_sep[0], msg="convert_MR"), unit_type(from_sep[1], msg="convert_MR")]
    if len(from_sep) == 3:
        from_types.append(unit_type(from_sep[2], msg="convert_MR"))
    to_types = [unit_type_o1(to_sep[0], msg="convert_MR"), unit_type(to_sep[1], msg="convert_MR")]
    if len(to_sep) == 3:
        to_types.append(unit_type(to_sep[2], msg="convert_MR"))
    if from_types != to_types:
        raise ValueError(
            "convert_MR: 'from' and 'to' unit types conflict.\n"
            "Rate unit strings should be in correct order: O2/Time or O2/Time/Mass or O2/Time/Area.\n"
            "See unit_args() for details.")
    if len(from_types) == 2:
        rate_type = "abs"
    elif from_types[2] == "mass":
        rate_type = "mass.spec"
    elif from_types[2] == "area":
        rate_type = "area.spec"
    else:
        raise ValueError(f"convert_MR: unit '{from_sep[2]}' not recognised as a mass or area unit.")

    f1 = units_val(from_sep[0], "o1")
    f2 = units_val(from_sep[1], "time")
    t1 = units_val(to_sep[0], "o1")
    t2 = units_val(to_sep[1], "time")
    if rate_type == "mass.spec":
        f3 = units_val(from_sep[2], "mass")
        t3 = units_val(to_sep[2], "mass")
    elif rate_type == "area.spec":
        f3 = units_val(from_sep[2], "area")
        t3 = units_val(to_sep[2], "area")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        rate_adj = adjust_scale(rate, f2, "hr.time")
        if rate_type == "mass.spec":
            rate_adj = adjust_scale(rate_adj, "kg.mass", f3)
        elif rate_type == "area.spec":
            rate_adj = adjust_scale_area(rate_adj, "m2.area", f3)
        ox_unit = units_val(f"{units_clean(f1, 'o1')}/l", "o2")
        rate_adj = convert_DO(rate_adj, ox_unit, "mg/l", S=S, t=t, P=P)
        out = convert_rate(rate_adj, oxy_unit="mg/l", time_unit="hour", output_unit=to,
                           volume=1, mass=1 if rate_type == "mass.spec" else None,
                           area=1 if rate_type == "area.spec" else None,
                           S=S, t=t, P=P, plot=False)
    rate_out_val = out.rate_output
    rate_out_un = out.output_unit

    if obj:
        # update the input object in place (mirrors respR)
        x.rate_output = np.asarray(rate_out_val)
        x.output_unit = rate_out_un
        x.summary["rate.output"] = np.asarray(rate_out_val)
        x.summary["output.unit"] = np.array([rate_out_un] * np.size(rate_out_val))
        x.summary["rate.abs"] = rate_out_val if rate_type == "abs" else x.summary.get("rate.abs")
        if rate_type == "mass.spec":
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                rates_abs = adjust_scale(np.asarray(x.summary["rate.abs"], dtype=float), f2, "hr.time")
                rates_abs = convert_DO(rates_abs, ox_unit, "mg/l", S=S, t=t, P=P)
                unit_abs = f"{to_sep[0]}/{to_sep[1]}"
                unit_abs = unit_abs.replace(".o2", "").replace(".time", "")
                rates_abs = convert_rate(rates_abs, oxy_unit="mg/l", time_unit="hour",
                                         output_unit=unit_abs, volume=1, S=S, t=t, P=P, plot=False).rate_output
            x.summary["rate.abs"] = np.asarray(rates_abs)
        x.call = None
        return x
    return rate_out_val
