"""select_rate all-methods comparison against R references.

R reference CSVs (tests/reference/ref_select_all_*.csv) were generated by
reference/gen_refs_select_all.R on R 4.5.3 + respR 2.3.4 using the same
dat2 -> calc_rate -> convert_rate pipeline as the Python side.
"""
import numpy as np
import pytest

import resprpy as p

from conftest import load_ref_csv  # noqa: F401  (helper import style)

METHODS = ["overlap", "duration", "density", "manual", "manual_omit",
           "time", "time_omit", "row", "row_omit", "oxygen", "oxygen_omit",
           "rsq", "intercept", "slope", "rep", "rep_omit", "rank",
           "rank_omit", "rate", "rate.output", "maximum_percentile",
           "minimum_percentile", "maximum", "minimum", "lowest_percentile",
           "highest_percentile", "lowest", "highest", "zero", "nonzero",
           "negative", "positive", "rolling", "linear"]
NVALS = {"overlap": 0, "duration": [0, 10], "density": None, "manual": 1,
         "manual_omit": 1, "time": [0, 80], "time_omit": [0, 80],
         "row": [1, 40], "row_omit": [1, 40], "oxygen": [6, 8],
         "oxygen_omit": [6, 8], "rsq": [0.5, 1], "intercept": [-1, 1],
         "slope": [-1, 1], "rep": 1, "rep_omit": 1, "rank": 1,
         "rank_omit": 1, "rate": [-1, 1], "rate.output": [-1, 1],
         "maximum_percentile": 0.5, "minimum_percentile": 0.5,
         "maximum": 1, "minimum": 1, "lowest_percentile": 0.5,
         "highest_percentile": 0.5, "lowest": 1, "highest": 1,
         "zero": None, "nonzero": None, "negative": None, "positive": None,
         "rolling": 1, "linear": None}
# methods for which R raises (density/linear need auto_rate linear input;
# rep/rep_omit need rep values which calc_rate objects do not carry)
R_ERR = {"density", "linear", "rep", "rep_omit"}
# numeric columns compared (mirrors gen_refs_select_all.R num_cols)
NUM_COLS = ["rep", "rank", "intercept_b0", "slope_b1", "rsq", "density",
            "row", "endrow", "time", "endtime", "oxy", "endoxy", "rate",
            "adjustment", "rate.adjusted", "rate.input", "volume", "mass",
            "area", "S", "t", "P", "rate.abs", "rate.m.spec",
            "rate.a.spec", "rate.output"]


def _setup():
    dat2 = np.genfromtxt("tests/reference/ref_adjust_dat2.csv",
                         delimiter=",", skip_header=1)
    cr = p.calc_rate(dat2, from_=[0, 100, 200], to=[80, 180, 280],
                     by="time", plot=False)
    cv = p.convert_rate(cr, oxy_unit="mg/L", time_unit="sec",
                        output_unit="mg/h/kg", volume=0.1, mass=0.01)
    return cv


def _load_ref(name):
    return np.genfromtxt(f"tests/reference/ref_select_all_{name}.csv",
                         delimiter=",", skip_header=1)


def test_select_rate_all_methods_status_matches_R():
    """Every method either succeeds like R or raises like R."""
    cv = _setup()
    for m in METHODS:
        try:
            p.select_rate(cv, m, n=NVALS[m])
            py_ok = True
        except Exception:
            py_ok = False
        assert py_ok != (m in R_ERR), (
            f"select_rate('{m}'): py OK={py_ok}, R OK={m not in R_ERR}")


def test_select_rate_all_methods_values_match_R():
    """Numeric summary values match R for every method that runs."""
    cv = _setup()
    for m in METHODS:
        if m in R_ERR:
            continue
        sr = p.select_rate(cv, m, n=NVALS[m])
        ref = _load_ref(m)
        # ref has 0 rows for some methods (nothing selected) -- compare
        # selected row/rank identity and numeric columns
        summ = sr.summary
        rank = np.asarray(summ["rank"], dtype=float)
        if ref.size == 0:
            assert rank.size == 0, f"{m}: py kept rows but R selected none"
            continue
        ref = np.atleast_2d(ref)  # single-row CSV comes back 1-D
        # R csv rows may carry NA rep/density cols; compare only cols present
        for j, col in enumerate(NUM_COLS):
            if col not in summ:
                continue
            ref_col = ref[:, j]
            if np.all(np.isnan(ref_col)):
                continue
            got = np.asarray(summ[col], dtype=float)
            if got.size != ref_col.size:
                # R csv includes rep/rank etc.; row count must match
                assert got.size == ref_col.size, (
                    f"{m}: {col} size {got.size} != R {ref_col.size}")
            with np.errstate(invalid="ignore"):
                ok = np.isclose(got, ref_col, rtol=1e-8, atol=1e-12,
                                equal_nan=True)
            assert np.all(ok), (
                f"{m}: {col} mismatch\n py={got}\n R ={ref_col}")
