"""Full re-implementation of the user's 0_RMR.R workflow in Python,
compared against R reference outputs generated by reference/gen_refs_0RMR.R.

Workflow per channel: read xlsx sheet 6 -> Date col 2 + Oxygen col 7 ->
format_time (elapsed seconds + 1) -> permeability correction ->
calc_rate over the meas_params cycles -> rate * 3600 -> summary columns
rank..rate (respR summary columns 2:13).
"""
import csv
import os

import numpy as np
import openpyxl

from resprpy import calc_rate, format_time
from conftest import REF_DIR, assert_close

DATADIR = r"X:\Rtools\20260422\20260509 5"
PARAMS_FILE = r"X:\Rtools\20260422\raw\meas_params.csv"
CHANNELS = [2, 3, 4, 5, 6, 7, 8, 9]

# permeability coefficients, channels 1-9 (0_RMR.R)
K_VALUES = [0.0006223, 0.000317161, 0.001055724, 0.000671915,
            0.000537423, 0.001256691, 0.000743536, 0.000743536, 0.000743536]


def read_meas_params(path, meas_time, rmr_type):
    """Find the unique params row for (meas_time, rmr_type)."""
    with open(path, encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))
    matches = [r for r in rows if int(r["meas_time"]) == meas_time
               and r["rmr_type"] == rmr_type]
    if len(matches) != 1:
        raise ValueError(f"expected exactly 1 params row for {meas_time}/{rmr_type}, got {len(matches)}")
    p = matches[0]
    return dict(cycles=int(p["cycles"]), cycle_length=int(p["cycle_length"]),
                initial=int(p["initial"]), cycle_start=int(p["cycle_start"]),
                cycle_time=int(p["cycle_time"]))


def build_cycles(params):
    """start/end times (s) for every cycle, exactly as 0_RMR.R."""
    cycle_time = params["cycle_time"] - params["cycle_start"] - 5
    starts = np.arange(params["cycle_start"] + params["initial"],
                       params["cycle_start"] + params["initial"]
                       + params["cycles"] * params["cycle_length"],
                       params["cycle_length"])
    ends = starts + cycle_time
    return starts, ends


def read_channel_sheet(xlsx_path, sheet_idx=6):
    """Columns 2 (Date) and 7 (Oxygen) of the given sheet (1-based)."""
    wb = openpyxl.load_workbook(xlsx_path, read_only=True, data_only=True)
    try:
        ws = wb.worksheets[sheet_idx - 1]
        rows = list(ws.iter_rows(values_only=True))
    finally:
        wb.close()
    data_rows = [r for r in rows[1:] if r[1] is not None]  # skip header row
    dates = [r[1] for r in data_rows]
    oxy = np.array([float(r[6]) for r in data_rows], dtype=float)
    return dates, oxy


def max_oxy_top30(oxygen):
    """mean of the 30 highest oxygen values (respR: order(decreasing)[1:min(30,n)])."""
    valid = oxygen[~np.isnan(oxygen)]
    k = min(30, valid.size)
    return float(np.mean(np.sort(valid)[-k:]))


def run_0RMR(xlsx_path, k_value, starts, ends):
    """The full per-channel 0_RMR.R pipeline; returns the summary array."""
    dates, oxygen = read_channel_sheet(xlsx_path)
    # data <- df[, c(2,7)]; format_time on the Date column (elapsed s + 1)
    _, time_num = format_time(np.array(dates, dtype=object).reshape(-1, 1), time=1, start=1)
    oxy_corr = oxygen - k_value * (max_oxy_top30(oxygen) - oxygen)
    data = np.column_stack([time_num, oxy_corr])
    cr = calc_rate(data, from_=starts, to=ends, by="time", plot=False)
    # the library generates the full summary table (respR column order);
    # take columns 2:13 (skip rep) and convert rate to mgO2/L/h, as 0_RMR.R
    s = cr.summary_table[:, 1:13].copy()
    s[:, -1] *= 3600
    assert cr.summary_columns[1:13] == ["rank", "intercept_b0", "slope_b1", "rsq",
                                        "row", "endrow", "time", "endtime",
                                        "oxy", "endoxy", "rate.2pt", "rate"]
    return s


def test_0RMR_full_workflow_against_R():
    params = read_meas_params(PARAMS_FILE, 20260509, "fish")
    starts, ends = build_cycles(params)
    assert params["cycles"] == 36
    assert starts[0] == 600 and ends[0] == 2155

    for ch in CHANNELS:
        out = run_0RMR(os.path.join(DATADIR, f"{ch}.xlsx"), K_VALUES[ch - 1], starts, ends)
        ref = np.genfromtxt(os.path.join(REF_DIR, f"ref_0RMR_file{ch}.csv"),
                            delimiter=",", skip_header=1)
        assert out.shape == ref.shape, (ch, out.shape, ref.shape)
        # ref columns: rank, intercept_b0, slope_b1, rsq, row, endrow, time,
        #              endtime, oxy, endoxy, rate.2pt, rate(already *3600)
        for j, name in enumerate(["rank", "intercept_b0", "slope_b1", "rsq",
                                  "row", "endrow", "time", "endtime", "oxy",
                                  "endoxy", "rate.2pt", "rate"]):
            rtol = 1e-8 if name in ("intercept_b0", "slope_b1", "oxy", "endoxy",
                                    "rate.2pt", "rate") else 1e-12
            assert_close(out[:, j], ref[:, j], rtol=rtol, atol=1e-12,
                         label=f"ch{ch} {name}")


def test_format_time_truncates_fractional_seconds():
    """R truncates fractional seconds in the POSIXct->character round trip
    (verified: 2.4/2.6/2.999 all format to '02'), so time must be integer."""
    from datetime import datetime, timedelta
    base = datetime(2026, 5, 9, 9, 38, 2)
    dates = np.array([[base], [base + timedelta(seconds=5.999)],
                      [base + timedelta(seconds=10.4)]], dtype=object)
    _, time_num = format_time(dates, time=1, start=1)
    assert np.all(time_num == np.array([1.0, 6.0, 11.0]))
